### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by SergeiGorbatiuk** [Maktu6/PyPatchMatch#1]
Hello! Thanks for the great work you've done!
I faced  some difficulties trying to build sources for this project. I find myself not so experienced in building c++ projects, so I wonder if you could help me with this one.
Here is an excerpt of console output:
```
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sergey/PyPatchMatch/build
[ 77%] Built target patchmatch
[ 88%] Building CXX object CMakeFiles/patchmatch_mat.dir/inpaint_mat.cpp.o
/home/sergey/PyPatchMatch/inpaint_mat.cpp: In function ‘cv::Mat inpaintPatchMatch_mat(cv::Mat, cv::Mat, int)’:
/home/sergey/PyPatchMatch/inpaint_mat.cpp:15:44: error: no matching function for call to ‘cv::Mat::Mat(IplImage*&)’
     cv::Mat output_mat = cv::Mat(output_img);
                                            ^
In file included from /usr/include/opencv2/core/mat.hpp:3518:0,
                 from /usr/include/opencv2/core.hpp:59,
                 from /usr/include/opencv2/opencv.hpp:52,
                 from /home/sergey/PyPatchMatch/inpaint_mat.hpp:1,
                 from /home/sergey/PyPatchMatch/inpaint_mat.cpp:1:
...
```
I have installed OpenCV as stated in the tutorial, and configured paths in setup.py. Is there anything else I am doing wrong?

**Comment by maktu6** [comment]
Which OpenCV version are you using? I only test the project in OpenCV 2.2.0.

**Comment by SergeiGorbatiuk** [comment]
Hi, thanks for your reply, but actually I do not remember what it was then:) I suppose, though, it was 3+, so it might be a resaon for crash.
Anyway, it is not actual as of now, and, if it seems nobody else faced this problem, we can close this issue
